import { Noto_Sans_TC } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

const notoSansTc = Noto_Sans_TC({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansTc.className}>
      <body>{children}</body>
    </html>
  );
}
